[package]
name = "simple-backup"
version = "0.1.0"
authors = ["shirokuro <46kuro212@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
xdg = "2"
log = "0.4"
pretty_env_logger = "0.4"
chrono = "0.4"
