#  ___(_)_ __ ___  _ __ | | ___      | |__   __ _  ___| | ___   _ _ __
# / __| | '_ ` _ \| '_ \| |/ _ \_____| '_ \ / _` |/ __| |/ / | | | '_ \
# \__ \ | | | | | | |_) | |  __/_____| |_) | (_| | (__|   <| |_| | |_) |
# |___/_|_| |_| |_| .__/|_|\___|     |_.__/ \__,_|\___|_|\_\\__,_| .__/
#                 |_|                                            |_|
# Simple backup tool using rsync.

# Executable of rsync
executable = "rsync"
# Target directory.
# All backups are created from this directory.
# **Please fill this value before use this tool**
target_dir = ""
# Destination directory.
# All backups are created in this directory.
# **Please fill this value before use this tool**
dest_dir = ""
